### ISSUE TITLE
Periodic high CPU load, due to busy looping

### ISSUE THREAD

**Issue by jackuess** [troglobit/ssdp-responder#12]
Hi and **thank you** for yet another great Troglobit project! :heart:

I have observed that ssdpd, periodically, eats quite a lot of cpu. This behavior is quite easy to amplify by setting the _interface refresh_ value low, while monitoring system load - with something like `top -o '%CPU' | grep ssdpd`. On an embedded system with few cores available it's easy to observe that ssdpd hogs the cpu periodically, but even on my PC laptop I can see it.

I think the issue is that `wait_message` will busy loop for a whole second when it has reached its timeout, happily eating all the cycles it can get a hold of. This can be observed by adding a trace log somewhere in the in the wait_message loop, like with this patch:
```
diff --git a/src/ssdpd.c b/src/ssdpd.c
index b02cc1c..0076f12 100644
--- a/src/ssdpd.c
+++ b/src/ssdpd.c
@@ -245,6 +245,7 @@ static void wait_message(time_t tmo)
 
 			err(1, "Unrecoverable error");
 		}
+		logit(LOG_INFO, "LOOP");
 	}
 }
```
...and run ssdp with 5 sec _refresh interval_:
```
 $ ssdpd -nlinfo -i5 2>&1 | ts
feb 02 20:57:22 Cannot create UUID cache, /var/db//ssdpd.cache: Permission denied
feb 02 20:57:22 No /etc/lsb-release found on system, using built-in server string.
feb 02 20:57:22 Server: POSIX UPnP/1.0 ssdpd/1.9
feb 02 20:57:22 Listening to HTTP connections on 0.0.0.0:1901
feb 02 20:57:22 Updating interfaces ...
feb 02 20:57:22 Sending SSDP NOTIFY on new interfaces ...
feb 02 20:57:22 Sending SSDP NOTIFY ...
feb 02 20:57:27 LOOP
feb 02 20:57:27 LOOP
feb 02 20:57:27 LOOP
...
feb 02 20:57:28 LOOP
feb 02 20:57:28 Updating interfaces ...
feb 02 20:57:33 LOOP
feb 02 20:57:33 LOOP
feb 02 20:57:33 LOOP
...
feb 02 20:57:34 LOOP
feb 02 20:57:34 Updating interfaces ...
```

I have a solution proposal in PR #11

**Comment by troglobit** [comment]
Awesome, thank you so much for reporting and fixing this, @jackuess <3

Sorry for the long response time, seems I had accidentally set this repo to "unwatch".

**Comment by jackuess** [comment]
Thank you, and no worries!

**Comment by troglobit** [comment]
New release coming in the next couple of days. Lots of new features :-)
