### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sresam89** [troglobit/ssdp-responder#2]
Would it be possible to add a list of neighbors and maintain it for timeout lookup?

Every time there is a response for msearch add the client details to a list
Compare the list with current time and the last time client notified the network and issue a time out after the timeout interval.

**Comment by troglobit** [comment]
I'm guessing this is for the very new tool ssdp-scan on the master branch?   I've modeled it on the behavior of the `mdns-scan` tool.

Sure, that could be done, and in many ways.  But why?

**Comment by sresam89** [comment]
Is the goal for the responder only be a reponder to incoming requests?

**Comment by troglobit** [comment]
That was the initial idea at least.  I needed something really simple for $DAYJOB that we could use on end-devices so Windows clients could find them. 

I've started playing around with the new `ssdp-scan` tool as a means to write automated tests for the responder.  

If you tell me a little bit more about what you're trying to do maybe I can gain an understanding for your feature request.

**Comment by troglobit** [comment]
ssdp-scan now works with ssdpd and the idea for an ssdpctl tool has been recorded as a TODO.
