### ISSUE TITLE
Not responding to Msearches

### ISSUE THREAD

**Issue by sresam89** [troglobit/ssdp-responder#3]
Current release deamon (ssdpd) is not responding to msearch from the sspd-scan

**Comment by troglobit** [comment]
If by "Current release" you mean the latest stuff on the master branch, then yeah.  The latest release is available in https://github.com/troglobit/ssdp-responder/releases

I've just started a huge refactoring of ssdpd, and also added the small helper tool ssdp-scan.  None of these are production ready yet.  I was meaning to finalize the work but have been sidetracked by some work related stuff.

**Comment by troglobit** [comment]
Fixed on master in 66ea000
