### ISSUE TITLE
ssdp-scan

### ISSUE THREAD

**Issue by lulululuej** [troglobit/ssdp-responder#5]
Hi,
I have download the opensource you provide and i want to use ssdp-scan, but there is no response and said command not found. Do i miss something?
Thank you.

**Comment by troglobit** [comment]
1) What did you download; git sources or the latest official release?
2) What do you do to build and install the package?

**Comment by lulululuej** [comment]
i use the command  " git clone https://github.com/troglobit/ssdp-responder " Is it wrong or i miss something?

**Comment by troglobit** [comment]
Unless you want to contribute changes to the project, I suggest you use the latest release, from the releases page, instead.

<https://github.com/troglobit/ssdp-responder/releases/>

Use the *versioned tarball*:

<https://github.com/troglobit/ssdp-responder/releases/download/v1.7/ssdp-responder-1.7.tar.gz>

Extract it and build, with the bundled `configure` script and the`make` tool on your system. You also need a C compiler:

    wget https://github.com/troglobit/ssdp-responder/releases/download/v1.7/ssdp-responder-1.7.tar.gz
    tar xf ssdp-responder-1.7.tar.gz
    cd ssdp-responder-1.7/
    ./configure
    make

When that is done you have the built `ssdp-scan` and `ssdpd` in `src/`.  You can now either run the programs from there, or install them on your system using:

    make install

This installs them into the default prefix `/usr/local`, which you can change by supplying a different prefix path to the configure script. See `./configure --help` for details.
