### ISSUE TITLE
SSDPD fail with openvpn

### ISSUE THREAD

**Issue by mmaret** [troglobit/ssdp-responder#6]
Hi,

First, thanks a lot for your software!

I'm trying to use it on a network with openvpn.
It's a TUN Server, and, on the client, the network configuration look like:

```
ip addr show tun0 
9: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
    link/none 
    inet 10.8.0.6 peer 10.8.0.5/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::5ad9:1f85:5605:8bd4/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```

As you can see, it's declare as a peer interface so ssdpd detect the netmask as 255.255.255.255.
Even if the route is correct
```
 ip route
default via 192.168.0.254 dev eno1 proto dhcp metric 100 
10.8.0.0/24 via 10.8.0.5 dev tun0 
...
```

So when an SSDP request is received, I can see
```
No matching socket for client 10.8.0.1
```

To work around this, I use this "as ugly as possible" patch:

```
diff --git a/src/ssdp.c b/src/ssdp.c
index 9198251..82e8e23 100644
--- a/src/ssdp.c
+++ b/src/ssdp.c
@@ -262,8 +262,13 @@ int ssdp_register(int sd, struct sockaddr *addr, struct sockaddr *mask, void (*c
 	ifs->cb   = cb;
 	if (address)
 		ifs->addr = *address;
-	if (mask)
+	if (mask){
+		if (netmask->sin_addr.s_addr == htonl(INADDR_BROADCAST)){
+			inet_aton("255.255.0.0", &netmask->sin_addr);
+			logit(LOG_DEBUG, "Changing mask");
+		}
 		ifs->mask = *netmask;
+	}
 	LIST_INSERT_HEAD(&il, ifs, link);
 
 	return 0;
```

Something better could be done, like checking the ifa_flags for IFF_POINTTOPOINT, but you may have some better idea!

Thanks again

**Comment by troglobit** [comment]
Hi, thanks for filing the report. I have no time to implement and test official support for this. Hopefully someone else has a similar setup and can help out.

**Comment by mmaret** [comment]
Thanks for having looking at it.

**Comment by mmaret** [comment]
To have a proper mask detection, I've change openvpn server configuration to have
`topology subnet`


This is now the recommended behavior for openVPN but not the default one for compatibility purpose.
If it's fine to you, I'll close the Issue

**Comment by troglobit** [comment]
Whatever works for you. If anyone runs into a similar issue, they might find this useful :)

**Comment by troglobit** [comment]
Decided to fix this one after all, neat to have a workaround for this case.  Only difference from your approach is to override with a /24 instead of /16.
